package model;
// Generated 12/04/2015 19:06:05 by Hibernate Tools 3.6.0


import dao.CursoDAO;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="scp"
)
public class Curso  implements java.io.Serializable {


     private int codigoCurso;
     private String nomeCurso;
     private Instituicao instituicao;
     private Orientador coordenador;
     private Tipocurso tipocurso;
     private Campus campus;
     
    

    public Curso() {
    }

    public Curso(int codigoCurso, String nomeCurso, Instituicao instituicao, Orientador coordenador, Tipocurso tipocurso, Campus campus) {
        this.codigoCurso = codigoCurso;
        this.nomeCurso = nomeCurso;
        this.instituicao = instituicao;
        this.coordenador = coordenador;
        this.tipocurso = tipocurso;
        this.campus = campus;
    }
    
     @Id 
    
    @Column(name="codigoCurso", unique=true, nullable=false)
    public int getCodigoCurso() {
        return this.codigoCurso;
    }
    
    public void setCodigoCurso(int codigoCurso) {
        this.codigoCurso = codigoCurso;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instituicao_codigo")
    public Instituicao getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campus_codigo")
    public Campus getCampus() {
        return campus;
    }

    public void setCampus(Campus campus) {
        this.campus = campus;
    }
    
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipoCurso_codigo")
    public Tipocurso getTipocurso() {
        return this.tipocurso;
    }
    
    public void setTipocurso(Tipocurso tipocurso) {
        this.tipocurso = tipocurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="coordenador")
    public Orientador getOrientador() {
        return this.coordenador;
    }
    
    public void setOrientador(Orientador coordenador) {
        this.coordenador = coordenador;
    }

    
    @Column(name="nomeCurso", length=45)
    public String getNomeCurso() {
        return this.nomeCurso;
    }
    
    public void setNomeCurso(String nomeCurso) {
        this.nomeCurso = nomeCurso;
    }

    public void gravar() throws SQLException, ClassNotFoundException {
        CursoDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        CursoDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        CursoDAO.excluir(this);
    }

    public static List<Curso> obterCursos()
            throws ClassNotFoundException, SQLException {
        return CursoDAO.obterCursos();
    }

    public static Curso obterCurso(int codigoCurso) throws ClassNotFoundException,
            SQLException {
        return CursoDAO.obterCurso(codigoCurso);
    }




}


