package model;
// Generated 12/04/2015 19:06:05 by Hibernate Tools 3.6.0


import dao.InstituicaoDAO;
import java.sql.SQLException;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Instituicao generated by hbm2java
 */
@Entity
@Table(name="instituicao"
    ,catalog="scp"
)
public class Instituicao  implements java.io.Serializable {


     private int codigoInstituicao;
     private String nomeInstituicao;

    public Instituicao() {
    }

	
    public Instituicao(int codigoInstituicao) {
        this.codigoInstituicao = codigoInstituicao;
    }
    public Instituicao(int codigoInstituicao, String nomeInstituicao) {
       this.codigoInstituicao = codigoInstituicao;
       this.nomeInstituicao = nomeInstituicao;
    }
   
     @Id 

    
    @Column(name="codigoInstituicao", unique=true, nullable=false)
    public int getCodigoInstituicao() {
        return this.codigoInstituicao;
    }
    
    public void setCodigoInstituicao(int codigoInstituicao) {
        this.codigoInstituicao = codigoInstituicao;
    }

    
    @Column(name="nomeInstituicao", length=45)
    public String getNomeInstituicao() {
        return this.nomeInstituicao;
    }
    
    public void setNomeInstituicao(String nomeInstituicao) {
        this.nomeInstituicao = nomeInstituicao;
    }
public void gravar() throws SQLException, ClassNotFoundException {
        InstituicaoDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        InstituicaoDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        InstituicaoDAO.excluir(this);
    }

    public static List<Instituicao> obterInstituicoes()
            throws ClassNotFoundException, SQLException {
        return InstituicaoDAO.obterInstituicoes();
    }

    public static Instituicao obterInstituicao(int codigoInstituicao) throws ClassNotFoundException,
            SQLException {
        return InstituicaoDAO.obterInstituicao(codigoInstituicao);
    }


}


