package model;
// Generated 12/04/2015 19:06:05 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pessoas generated by hbm2java
 */
@Entity
@Table(name="pessoas"
    ,catalog="scp"
)
public class Pessoas  implements java.io.Serializable {
    
     private int codigo;
     private Campus campus;
     private String nome;
     private String dataNascimento;
     private String estadoCivil;
     private String nacionalidade;
     private String ufNascimento;
     private String nomeMae;
     private String nomePai;
     private String naturalidade;
     private String grupoSanguineo;
     private String fatorRh;
     private String sexo;
     private String necessidadeEspecial;
     private String cor;
     private String escolaridade;
     private String rua;
     private int numero;
     private String complemento;
     private String bairro;
     private String cidade;
     private int cep;
     private String uf;
     private String pais;
     private String email;
     private int rg;
     private String orgaoExpedidor;
     private int tituloEleitor;
     private Integer numeroComprovanteMilitar;
     private int cpf;
     private Integer pisPasep;
     private String dataExpedicaoRg;

     
    public Pessoas() {
    }
     
    public Pessoas(int codigo, Campus campus, String nome, String dataNascimento, String estadoCivil, String nacionalidade, String ufNascimento, String nomeMae, String nomePai, String naturalidade, String grupoSanguineo, String fatorRh, String sexo, String necessidadeEspecial, String cor, String escolaridade, String rua, int numero, String complemento, String bairro, String cidade, int cep, String uf, String pais, String email, int rg, String orgaoExpedidor, int tituloEleitor, int numeroComprovanteMilitar, int cpf, int pisPasep, String dataExpedicaoRg) {
        this.codigo = codigo;
        this.campus = campus;
        this.nome = nome;
        this.dataNascimento = dataNascimento;
        this.estadoCivil = estadoCivil;
        this.nacionalidade = nacionalidade;
        this.ufNascimento = ufNascimento;
        this.nomeMae = nomeMae;
        this.nomePai = nomePai;
        this.naturalidade = naturalidade;
        this.grupoSanguineo = grupoSanguineo;
        this.fatorRh = fatorRh;
        this.sexo = sexo;
        this.necessidadeEspecial = necessidadeEspecial;
        this.cor = cor;
        this.escolaridade = escolaridade;
        this.rua = rua;
        this.numero = numero;
        this.complemento = complemento;
        this.bairro = bairro;
        this.cidade = cidade;
        this.cep = cep;
        this.uf = uf;
        this.pais = pais;
        this.email = email;
        this.rg = rg;
        this.orgaoExpedidor = orgaoExpedidor;
        this.tituloEleitor = tituloEleitor;
        this.numeroComprovanteMilitar = numeroComprovanteMilitar;
        this.cpf = cpf;
        this.pisPasep = pisPasep;
        this.dataExpedicaoRg = dataExpedicaoRg;
    }
    
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
   
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campus_codigo", nullable=false)
    
    public Campus getCampus(){
        return this.campus;
    }
    
    public void setCampus(Campus campus){
        this.campus=campus;
    }
    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="dataNascimento", nullable=false, length=11)
    public String getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="estadoCivil", nullable=false, length=45)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="nacionalidade", nullable=false, length=45)
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    
    @Column(name="ufNascimento", nullable=false, length=2)
    public String getUfNascimento() {
        return this.ufNascimento;
    }
    
    public void setUfNascimento(String ufNascimento) {
        this.ufNascimento = ufNascimento;
    }

    
    @Column(name="nomeMae", nullable=false, length=45)
    public String getNomeMae() {
        return this.nomeMae;
    }
    
    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }

    
    @Column(name="nomePai", nullable=false, length=45)
    public String getNomePai() {
        return this.nomePai;
    }
    
    public void setNomePai(String nomePai) {
        this.nomePai = nomePai;
    }

    
    @Column(name="naturalidade", nullable=false, length=45)
    public String getNaturalidade() {
        return this.naturalidade;
    }
    
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }

    
    @Column(name="grupoSanguineo", nullable=false, length=2)
    public String getGrupoSanguineo() {
        return this.grupoSanguineo;
    }
    
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }

    
    @Column(name="fatorRH", nullable=false, length=10)
    public String getFatorRh() {
        return this.fatorRh;
    }
    
    public void setFatorRh(String fatorRh) {
        this.fatorRh = fatorRh;
    }

    
    @Column(name="sexo", nullable=false, length=45)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="necessidadeEspecial", nullable=false, length=45)
    public String getNecessidadeEspecial() {
        return this.necessidadeEspecial;
    }
    
    public void setNecessidadeEspecial(String necessidadeEspecial) {
        this.necessidadeEspecial = necessidadeEspecial;
    }

    
    @Column(name="cor", nullable=false, length=45)
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }

    
    @Column(name="escolaridade", nullable=false, length=45)
    public String getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }

    
    @Column(name="rua", nullable=false, length=45)
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }

    
    @Column(name="numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    
    @Column(name="complemento", nullable=false, length=45)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="bairro", nullable=false, length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", nullable=false, length=45)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="cep", nullable=false)
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }

    
    @Column(name="uf", nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="pais", nullable=false, length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="rg", nullable=false)
    public int getRg() {
        return this.rg;
    }
    
    public void setRg(int rg) {
        this.rg = rg;
    }

    
    @Column(name="orgaoExpedidor", nullable=false, length=45)
    public String getOrgaoExpedidor() {
        return this.orgaoExpedidor;
    }
    
    public void setOrgaoExpedidor(String orgaoExpedidor) {
        this.orgaoExpedidor = orgaoExpedidor;
    }

    
    @Column(name="tituloEleitor", nullable=false)
    public int getTituloEleitor() {
        return this.tituloEleitor;
    }
    
    public void setTituloEleitor(int tituloEleitor) {
        this.tituloEleitor = tituloEleitor;
    }

    
    @Column(name="numeroComprovanteMilitar")
    public Integer getNumeroComprovanteMilitar() {
        return this.numeroComprovanteMilitar;
    }
    
    public void setNumeroComprovanteMilitar(Integer numeroComprovanteMilitar) {
        this.numeroComprovanteMilitar = numeroComprovanteMilitar;
    }

    
    @Column(name="cpf", nullable=false)
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="pisPasep")
    public Integer getPisPasep() {
        return this.pisPasep;
    }
    
    public void setPisPasep(Integer pisPasep) {
        this.pisPasep = pisPasep;
    }

    
    @Column(name="dataExpedicaoRG", nullable=false, length=11)
    public String getDataExpedicaoRg() {
        return this.dataExpedicaoRg;
    }
    
    public void setDataExpedicaoRg(String dataExpedicaoRg) {
        this.dataExpedicaoRg = dataExpedicaoRg;
    }

}


