package model;
// Generated 12/04/2015 19:06:05 by Hibernate Tools 3.6.0

import dao.ProjetoDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projeto generated by hbm2java
 */
@Entity
@Table(name = "projeto", catalog = "scp"
)
public class Projeto implements java.io.Serializable {

    private int codigoProjeto;
    private Orientador orientador;
    private Tipobolsa tipobolsa;
    private Edital edital;
    private SubArea subareaconhecimento;
    private String nomeProjeto;
    private int cargaHoraria;
    private String palavraChave;
    private int duracaoProjeto;
    private String dataInicio;
    private String dataTermino;
    private Float valorfinanciamento;
    private String dataFinanciamento;
    private String programa;
    private String agenciaFomento;
    private int quantidadeBolsa;
    private String instituicaoParceira;
    private String coOrientador;
    private String grupoPesquisaCNPq;

    public Projeto() {
    }

    public Projeto(int codigoProjeto, String nomeProjeto, int cargaHoraria, String palavraChave, int duracaoProjeto, String dataInicio, String dataTermino, float valorfinanciamento, String dataFinanciamento, String programa, String agenciaFomento, int quantidadeBolsa, String instituicaoParceira, String grupoPesquisaCNPq, String coOrientador, Tipobolsa tipoBolsa, Edital edital, SubArea subArea, Orientador coordenador) {
        this.codigoProjeto = codigoProjeto;
        this.nomeProjeto = nomeProjeto;
        this.cargaHoraria = cargaHoraria;
        this.palavraChave = palavraChave;
        this.duracaoProjeto = duracaoProjeto;
        this.dataInicio = dataInicio;
        this.dataTermino = dataTermino;
        this.valorfinanciamento = valorfinanciamento;
        this.dataFinanciamento = dataFinanciamento;
        this.programa = programa;
        this.agenciaFomento = agenciaFomento;
        this.quantidadeBolsa = quantidadeBolsa;
        this.instituicaoParceira = instituicaoParceira;
        this.grupoPesquisaCNPq = grupoPesquisaCNPq;
        this.coOrientador = coOrientador;
        this.edital = edital;
        this.tipobolsa = tipoBolsa;
        this.subareaconhecimento = subArea;
        this.orientador = coordenador;

    }

    @Id

    @Column(name = "codigoProjeto", unique = true, nullable = false)
    public int getCodigoProjeto() {
        return this.codigoProjeto;
    }

    public void setCodigoProjeto(int codigoProjeto) {
        this.codigoProjeto = codigoProjeto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orientador_codigo", nullable = false)
    public Orientador getOrientador() {
        return this.orientador;
    }

    public void setOrientador(Orientador orientador) {
        this.orientador = orientador;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipobolsa_codigo", nullable = false)
    public Tipobolsa getTipobolsa() {
        return this.tipobolsa;
    }

    public void setTipobolsa(Tipobolsa tipobolsa) {
        this.tipobolsa = tipobolsa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "edital_codigo", nullable = false)
    public Edital getEdital() {
        return this.edital;
    }

    public void setEdital(Edital edital) {
        this.edital = edital;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subareaconhecimento_codigo", nullable = false)
    public SubArea getSubareaconhecimento() {
        return this.subareaconhecimento;
    }

    public void setSubareaconhecimento(SubArea subareaconhecimento) {
        this.subareaconhecimento = subareaconhecimento;
    }

    @Column(name = "nomeProjeto", nullable = false, length = 45)
    public String getNomeProjeto() {
        return this.nomeProjeto;
    }

    public void setNomeProjeto(String nomeProjeto) {
        this.nomeProjeto = nomeProjeto;
    }

    @Column(name = "cargaHoraria", nullable = false)
    public int getCargaHoraria() {
        return this.cargaHoraria;
    }

    public void setCargaHoraria(int cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    @Column(name = "palavrachave", nullable = false, length = 45)
    public String getPalavrachave() {
        return this.palavraChave;
    }

    public void setPalavrachave(String palavrachave) {
        this.palavraChave = palavrachave;
    }

    @Column(name = "duracaoProjeto", nullable = false)
    public int getduracaoProjeto() {
        return this.duracaoProjeto;
    }

    public void setduracaoProjeto(int duracaoProjeto) {
        this.duracaoProjeto = duracaoProjeto;
    }

    @Column(name = "dataInicio", nullable = false, length = 11)
    public String getDataInicio() {
        return this.dataInicio;
    }

    public void setDataInicio(String dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Column(name = "dataTermino", nullable = false, length = 11)
    public String getDataTermino() {
        return this.dataTermino;
    }

    public void setDataTermino(String dataTermino) {
        this.dataTermino = dataTermino;
    }

    @Column(name = "valorFinanciamento", precision = 12, scale = 0)
    public Float getValorFinanciamento() {
        return this.valorfinanciamento;
    }

    public void setValorFinanciamento(Float valorFinanciamento) {
        this.valorfinanciamento = valorFinanciamento;
    }

    @Column(name = "dataFinanciamento", length = 11)
    public String getDataFinanciamento() {
        return this.dataFinanciamento;
    }

    public void setDataFinanciamento(String dataFinanciamento) {
        this.dataFinanciamento = dataFinanciamento;
    }

    @Column(name = "programa", nullable = false, length = 45)
    public String getPrograma() {
        return this.programa;
    }

    public void setPrograma(String programa) {
        this.programa = programa;
    }

    @Column(name = "agenciaFomento", nullable = false, length = 45)
    public String getAgenciaFomento() {
        return this.agenciaFomento;
    }

    public void setAgenciaFomento(String agenciaFomento) {
        this.agenciaFomento = agenciaFomento;
    }

    @Column(name = "quantidadeBolsa", nullable = false)
    public int getquantidadeBolsa() {
        return this.quantidadeBolsa;
    }

    public void setquantidadeBolsa(int quantidadeBolsa) {
        this.quantidadeBolsa = quantidadeBolsa;
    }

    @Column(name = "instituicaoParceira", length = 45)
    public String getInstituicaoParceira() {
        return this.instituicaoParceira;
    }

    public void setInstituicaoParceira(String instituicaoParceira) {
        this.instituicaoParceira = instituicaoParceira;
    }

    @Column(name = "coOrientador", length = 45)
    public String getcoOrientador() {
        return this.coOrientador;
    }

    public void setcoOrientador(String coOrientador) {
        this.coOrientador = coOrientador;
    }
    
    public void setCoOrientador(String coOrientador) {
        this.coOrientador = coOrientador;
    }

    @Column(name = "grupoPesquisaCNPq", length = 45)
    public String getGrupoPesquisaCNPq() {
        return this.grupoPesquisaCNPq;
    }

    public void setGrupoPesquisaCNPq(String grupoPesquisaCnpq) {
        this.grupoPesquisaCNPq = grupoPesquisaCNPq;
    }

    public void gravar() throws SQLException, ClassNotFoundException {
        ProjetoDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        ProjetoDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        ProjetoDAO.excluir(this);
    }

    public static List<Projeto> obterProjetos()
            throws ClassNotFoundException, SQLException {
        return ProjetoDAO.obterProjetos();
    }

    public static Projeto obterProjeto(int codigoProjeto) throws ClassNotFoundException,
            SQLException {
        return ProjetoDAO.obterProjeto(codigoProjeto);
    }

}
