package model;
// Generated 12/04/2015 19:06:05 by Hibernate Tools 3.6.0


import dao.SubAreaDAO;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *SubAreao generated by hbm2java
 */
@Entity
@Table(name="subareaconhecimento"
    ,catalog="scp"
)
public class SubArea  implements java.io.Serializable {


     private int codigoSubArea;
     private String nomeSubArea;
    
    public SubArea() {
    }

	
    public SubArea(int codigoSubArea, String nomeSubArea) {
        this.codigoSubArea = codigoSubArea;
        this.nomeSubArea = nomeSubArea;
    }    
    
    
    @Id 
    @Column(name="codigoSubArea", unique=true, nullable=false)
    public int getCodigoSubArea() {
        return this.codigoSubArea;
    }
    
    public void setCodigoSubArea(int codigoSubArea) {
        this.codigoSubArea = codigoSubArea;
    }

    
    @Column(name="nomeSubArea", nullable=false, length=45)
    public String getNomeSubArea() {
        return this.nomeSubArea;
    }
    
    public void setNomeSubArea(String nomeSubArea) {
        this.nomeSubArea = nomeSubArea;
    }

     public void gravar() throws SQLException, ClassNotFoundException {
        SubAreaDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        SubAreaDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        SubAreaDAO.excluir(this);
    }

    public static List<SubArea> obterSubAreas()
            throws ClassNotFoundException, SQLException {
        return SubAreaDAO.obterSubAreas();
    }

    public static SubArea obterSubArea(int codigoSubArea) throws ClassNotFoundException,
            SQLException {
        return SubAreaDAO.obterSubArea(codigoSubArea);
    }

    
    
    
}


