package model;
// Generated 12/04/2015 19:06:05 by Hibernate Tools 3.6.0



import dao.TipoBolsaDAO;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *Tipobolsaa generated by hbm2java
 */
@Entity
@Table(name="tipobolsa"
    ,catalog="scp"
)
public class Tipobolsa  implements java.io.Serializable {


     private int codigoTipoBolsa;
     private String nomeTipoBolsa;

    public Tipobolsa() {
    }

	
    public Tipobolsa(int codigoTipoBolsa) {
        this.codigoTipoBolsa = codigoTipoBolsa;
    }
    public Tipobolsa(int codigoTipoBolsa, String nomeTipoBolsa) {
       this.codigoTipoBolsa = codigoTipoBolsa;
       this.nomeTipoBolsa = nomeTipoBolsa;
      
    }
   
     @Id 

    @Column(name="codigoTipoBolsa", unique=true, nullable=false)
    public int getCodigoTipoBolsa() {
        return this.codigoTipoBolsa;
    }
    
    public void setCodigoTipoBolsa(int codigoTipoBolsa) {
        this.codigoTipoBolsa = codigoTipoBolsa;
    }

    
    @Column(name="nomeTipoBolsa", length=45)
    public String getNomeTipoBolsa() {
        return this.nomeTipoBolsa;
    }
    
    public void setNomeTipoBolsa(String nomeTipoBolsa) {
        this.nomeTipoBolsa = nomeTipoBolsa;
    }

     public void gravar() throws SQLException, ClassNotFoundException {
        TipoBolsaDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        TipoBolsaDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        TipoBolsaDAO.excluir(this);
    }

    public static List<Tipobolsa> obterTipoBolsas()
            throws ClassNotFoundException, SQLException {
        return TipoBolsaDAO.obterTipoBolsas();
    }

    public static Tipobolsa obterTipoBolsa(int codigoTipoBolsa) throws ClassNotFoundException,
            SQLException {
        return TipoBolsaDAO.obterTipoBolsa(codigoTipoBolsa);
    }




}